[theme]
## Theme 1 Dark Theme
# primaryColor="#0d6e6e"
# backgroundColor="#0d1f2d"
# secondaryBackgroundColor="#1d2e3d"
# textColor="#ffffff"

## Dark Gray and yellow theme
# primaryColor="#da8e0f"
# backgroundColor="#1e1e1e"
# secondaryBackgroundColor="#2d2d2d"
# textColor="#dcdcdc"

## Dark Blue and yellow theme
# primaryColor="#ffc107"
# backgroundColor="#0b0f2b"
# secondaryBackgroundColor="#1a1e3b"
# textColor="#ffffff"

## Dark Purple Theme
# primaryColor="#864879"
# backgroundColor="#1F1D36"
# secondaryBackgroundColor="#3F3351"
# textColor="#ffffff"

## Dark Purple Theme
# primaryColor="#3C2A21"
# backgroundColor="#1A120B"
# secondaryBackgroundColor="#3C2A21"
# textColor="#ffffff"

## Sleek Green Theme
primaryColor="#d69d6b"
backgroundColor="#263531"
secondaryBackgroundColor="#192421"
textColor="#D1E8E2"
